version: 2
updates:
  # github-actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    commit-message:
      prefix: "dependabot(github): "
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    assignees:
      - "djerfy"
    reviewers:
      - "djerfy"
  # python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    commit-message:
      prefix: "dependabot(pip): "
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    assignees:
      - "djerfy"
    reviewers:
      - "djerfy"
  # docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    commit-message:
      prefix: "dependabot(docker): "
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
    assignees:
      - "djerfy"
    reviewers:
      - "djerfy"
